version: '3'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - logs:/app/logs
    ports:
      - '8000:8000'
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
    volumes:
      - logs:/app/logs
    ports:
      - '9000:9000'
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    volumes:
      - ./dump.rdb:/data/dump.rdb
    command: ['redis-server', '--dir', '/data', '--dbfilename', 'dump.rdb']
    ports:
      - '6379:6379'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - frontend-build:/app/build

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-build:
  logs:
